Imports System
Imports System.Web.UI
<Assembly: TagPrefix("_Library", "MyLibrary")> 
<Assembly: TagPrefix("_Library._Web.MultiControl", "MC")> 
<Assembly: TagPrefix("_Library._Web.FlexGrid", "FG")> 
<Assembly: TagPrefix("_Library._Web.DbLookup", "DBL")> 
<Assembly: TagPrefix("_Library._Web.MultiControl.McScriptManager", "MCSM")> 
<Assembly: System.Web.UI.WebResource("test.js", "text/javascript")> 
<Assembly: System.Web.UI.WebResource("about.html", "text/html")> 
<Assembly: System.Web.UI.WebResource("blank.html", "text/html")> 
<Assembly: System.Web.UI.WebResource("custom2.html", "text/html")> 
<Assembly: System.Web.UI.WebResource("ed_about.jpg", "img/jpg")> 
<Assembly: System.Web.UI.WebResource("ed_align_center.jpg", "img/jpg")> 
<Assembly: System.Web.UI.WebResource("ed_align_left.jpg", "img/jpg")> 
<Assembly: System.Web.UI.WebResource("ed_align_right.jpg", "img/jpg")> 
<Assembly: System.Web.UI.WebResource("ed_blank.jpg", "img/jpg")> 
<Assembly: System.Web.UI.WebResource("ed_charmap.jpg", "img/jpg")> 
<Assembly: System.Web.UI.WebResource("ed_color_bg.jpg", "img/jpg")> 
<Assembly: System.Web.UI.WebResource("ed_color_fg.jpg", "img/jpg")> 
<Assembly: System.Web.UI.WebResource("ed_copy.jpg", "img/jpg")> 
<Assembly: System.Web.UI.WebResource("ed_removehtml.jpg", "img/jpg")> 
<Assembly: System.Web.UI.WebResource("ed_custom.jpg", "img/jpg")> 
<Assembly: System.Web.UI.WebResource("ed_cut.jpg", "img/jpg")> 
<Assembly: System.Web.UI.WebResource("ed_delete.jpg", "img/jpg")> 
<Assembly: System.Web.UI.WebResource("ed_format_bold.jpg", "img/jpg")> 
<Assembly: System.Web.UI.WebResource("ed_format_italic.jpg", "img/jpg")> 
<Assembly: System.Web.UI.WebResource("ed_format_strike.jpg", "img/jpg")> 
<Assembly: System.Web.UI.WebResource("ed_format_sub.jpg", "img/jpg")> 
<Assembly: System.Web.UI.WebResource("ed_format_sup.jpg", "img/jpg")> 
<Assembly: System.Web.UI.WebResource("ed_format_underline.jpg", "img/jpg")> 
<Assembly: System.Web.UI.WebResource("ed_help.jpg", "img/jpg")> 
<Assembly: System.Web.UI.WebResource("ed_hr.jpg", "img/jpg")> 
<Assembly: System.Web.UI.WebResource("ed_html.jpg", "img/jpg")> 
<Assembly: System.Web.UI.WebResource("ed_image.jpg", "img/jpg")> 
<Assembly: System.Web.UI.WebResource("ed_indent_less.jpg", "img/jpg")> 
<Assembly: System.Web.UI.WebResource("ed_indent_more.jpg", "img/jpg")> 
<Assembly: System.Web.UI.WebResource("ed_link.jpg", "img/jpg")> 
<Assembly: System.Web.UI.WebResource("ed_list_bullet.jpg", "img/jpg")> 
<Assembly: System.Web.UI.WebResource("ed_list_num.jpg", "img/jpg")> 
<Assembly: System.Web.UI.WebResource("ed_redo.jpg", "img/jpg")> 
<Assembly: System.Web.UI.WebResource("ed_undo.jpg", "img/jpg")> 
<Assembly: System.Web.UI.WebResource("editor_help.html", "text/html")> 
<Assembly: System.Web.UI.WebResource("fullscreen.html", "text/html")> 
<Assembly: System.Web.UI.WebResource("fullscreen_maximize.jpg", "img/jpg")> 
<Assembly: System.Web.UI.WebResource("fullscreen_minimize.jpg", "img/jpg")> 
<Assembly: System.Web.UI.WebResource("insert_image.html", "text/html")> 
<Assembly: System.Web.UI.WebResource("insert_table.html", "text/html")> 
<Assembly: System.Web.UI.WebResource("insert_table.jpg", "img/jpg")> 
<Assembly: System.Web.UI.WebResource("select_color.html", "text/html")> 
<Assembly: System.Web.UI.WebResource("AddRowAbove.jpg", "img/jpg")> 
<Assembly: System.Web.UI.WebResource("AddRowBelow.jpg", "img/jpg")> 
<Assembly: System.Web.UI.WebResource("DeleteRow.jpg", "img/jpg")> 

